version: "3"

tasks:
  air:
    aliases:
      - air
    desc: "Generate grpc proto file"
    cmds:
      - air
  build:
    desc: "Building go project"
    cmds:
      - go build -o .bin/main cmd/main/main.go
    generates:
      - bin/main
  run:
    aliases:
      - run
    desc: "Build and run the Go project"
    deps:
     - build
    cmds:
      - ./bin/main

